### ISSUE TITLE
有考虑过实现.5pxborder方案么？

### ISSUE THREAD

**Issue by guyunxiang** [saltjs/salt-ui#33]
现在手机分辨率普遍很好，已经不是一两年钱的640x320年代，1pxborder显示效果较原生border而言偏粗，校验统一一下.5pxborder标准，统一按照这个标准设计组件，效果更好。

**Comment by gbk** [comment]
支持 0.5px 的设备在 html 结点上有 hairline 样式，
可这样定义：
```css
.hairline .onepx { border: 0.5px solid red }
```
